In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)

In [4]:
from pathlib import Path


# Load datasets
demographics = pd.read_csv(r"C:\Users\User\Downloads\demographics_clean.csv")
vitals = pd.read_csv(r"C:\Users\User\OneDrive\Documents\vitals_clean.csv")
adverse_events = pd.read_csv(r"C:\Users\User\OneDrive\Documents\adverse_event_clean.csv")
lab_results = pd.read_csv(r"C:\Users\User\OneDrive\Documents\lab_results_clean.csv")

print("All datasets loaded successfully.")

All datasets loaded successfully.

In [5]:
# Check the first 5 rows of each dataset

print("DEMOGRAPHICS")
display(demographics.head())

print("\nVITAL SIGNS")
display(vitals.head())

print("\nADVERSE EVENTS")
display(adverse_events.head())

print("\nLAB RESULTS")
display(lab_results.head())

DEMOGRAPHICS

  SUBJECT_ID  SITE_ID ENROLL_DATE   AGE SEX          ARM      AGE_FLAG
0    SUB-001  SITE-01  12-01-2025   5.0   M  Treatment A  OUT_OF_RANGE
1    SUB-002  SITE-02  10-02-2025  50.0   M      Placebo            OK
2    SUB-003  SITE-01  06-06-2025  61.0   F  Treatment A            OK
3    SUB-004  SITE-01  29-01-2025  73.0   M  Treatment A            OK
4    SUB-005  SITE-01  29-05-2025  48.0   M      Placebo            OK

VITAL SIGNS

,SUBJECT_ID,VISIT,VISIT_DATE,SYSTOLIC_BP,DIASTOLIC_BP,HEART_RATE,TEMP_C,WEIGHT_KG,BP_FLAG,TEMP_FLAG,ENROLL_DATE,VISIT_BEFORE_ENROLL_FLAG
0,SUB-001,Screening,13-01-2025,115,76.0,62,36.4,82.6,OK,OK,12-01-2025,OK
1,SUB-001,Week 4,11-03-2025,140,77.0,84,42.5,63.6,OK,OUT_OF_RANGE,12-01-2025,OK
2,SUB-001,Week 8,05-04-2025,127,91.0,73,37.3,37.9,OK,OK,12-01-2025,OK
3,SUB-002,Screening,11-02-2025,133,78.0,71,36.8,46.2,OK,OK,10-02-2025,OK
4,SUB-002,Baseline,12-03-2025,118,81.0,88,36.6,61.5,OK,OK,10-02-2025,OK

ADVERSE EVENTS

,AE_ID,SUBJECT_ID,AE_TERM,START_DATE,END_DATE,SEVERITY,RELATEDNESS,OUTCOME,MISSING_START_FLAG,MISSING_SEVERITY_FLAG,DATE_LOGIC_FLAG
0,AE-0001,SUB-001,Injection site reaction,04-02-2025,18-02-2025,Mild,Not Related,Resolved,OK,OK,OK
1,AE-0002,SUB-001,Rash,17-01-2025,18-01-2025,Moderate,Not Related,Resolved,OK,OK,OK
2,AE-0003,SUB-004,Injection site reaction,16-02-2025,05-03-2025,Moderate,Related,Ongoing,OK,OK,OK
3,AE-0004,SUB-004,Insomnia,01-05-2025,07-05-2025,Mild,Not Related,Ongoing,OK,OK,OK
4,AE-0005,SUB-005,Diarrhea,23-07-2025,09-08-2025,Moderate,Not Related,Resolved,OK,OK,OK

LAB RESULTS

,SUBJECT_ID,VISIT,VISIT_DATE,TEST_NAME,RESULT,UNIT,NORMAL_LOW,NORMAL_HIGH,RESULT_FLAG
0,SUB-001,Baseline,09-02-2025,ALT,38.71,U/L,7.0,56.0,WITHIN_RANGE
1,SUB-001,Baseline,09-02-2025,AST,24.96,U/L,8.0,48.0,WITHIN_RANGE
2,SUB-001,Baseline,09-02-2025,Hemoglobin,16.91,g/dL,12.0,17.5,WITHIN_RANGE
3,SUB-001,Baseline,09-02-2025,WBC,6.58,10^9/L,4.0,11.0,WITHIN_RANGE
4,SUB-001,Baseline,09-02-2025,Creatinine,0.95,mg/dL,0.6,1.3,WITHIN_RANGE

In [6]:
# Check rows, columns, data types and missing values

datasets = {
    "Demographics": demographics,
    "Vitals": vitals,
    "Adverse Events": adverse_events,
    "Lab Results": lab_results
}

for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)

    print("\nShape:", df.shape)

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

============================================================
DEMOGRAPHICS
============================================================

Shape: (60, 7)

Column Names:
['SUBJECT_ID', 'SITE_ID', 'ENROLL_DATE', 'AGE', 'SEX', 'ARM', 'AGE_FLAG']

Data Types:
SUBJECT_ID      object
SITE_ID         object
ENROLL_DATE     object
AGE            float64
SEX             object
ARM             object
AGE_FLAG        object
dtype: object

Missing Values:
SUBJECT_ID     0
SITE_ID        0
ENROLL_DATE    0
AGE            3
SEX            0
ARM            0
AGE_FLAG       0
dtype: int64

============================================================
VITALS
============================================================

Shape: (281, 12)

Column Names:
['SUBJECT_ID', 'VISIT', 'VISIT_DATE', 'SYSTOLIC_BP', 'DIASTOLIC_BP', 'HEART_RATE', 'TEMP_C', 'WEIGHT_KG', 'BP_FLAG', 'TEMP_FLAG', 'ENROLL_DATE', 'VISIT_BEFORE_ENROLL_FLAG']

Data Types:
SUBJECT_ID                   object
VISIT                        object
VISIT_DATE                   object
SYSTOLIC_BP                   int64
DIASTOLIC_BP                float64
HEART_RATE                    int64
TEMP_C                      float64
WEIGHT_KG                   float64
BP_FLAG                      object
TEMP_FLAG                    object
ENROLL_DATE                  object
VISIT_BEFORE_ENROLL_FLAG     object
dtype: object

Missing Values:
SUBJECT_ID                  0
VISIT                       0
VISIT_DATE                  0
SYSTOLIC_BP                 0
DIASTOLIC_BP                6
HEART_RATE                  0
TEMP_C                      0
WEIGHT_KG                   0
BP_FLAG                     0
TEMP_FLAG                   0
ENROLL_DATE                 0
VISIT_BEFORE_ENROLL_FLAG    0
dtype: int64

============================================================
ADVERSE EVENTS
============================================================

Shape: (51, 11)

Column Names:
['AE_ID', 'SUBJECT_ID', 'AE_TERM', 'START_DATE', 'END_DATE', 'SEVERITY', 'RELATEDNESS', 'OUTCOME', 'MISSING_START_FLAG', 'MISSING_SEVERITY_FLAG', 'DATE_LOGIC_FLAG']

Data Types:
AE_ID                    object
SUBJECT_ID               object
AE_TERM                  object
START_DATE               object
END_DATE                 object
SEVERITY                 object
RELATEDNESS              object
OUTCOME                  object
MISSING_START_FLAG       object
MISSING_SEVERITY_FLAG    object
DATE_LOGIC_FLAG          object
dtype: object

Missing Values:
AE_ID                    0
SUBJECT_ID               0
AE_TERM                  0
START_DATE               1
END_DATE                 0
SEVERITY                 2
RELATEDNESS              0
OUTCOME                  0
MISSING_START_FLAG       0
MISSING_SEVERITY_FLAG    0
DATE_LOGIC_FLAG          0
dtype: int64

============================================================
LAB RESULTS
============================================================

Shape: (1100, 9)

Column Names:
['SUBJECT_ID', 'VISIT', 'VISIT_DATE', 'TEST_NAME', 'RESULT', 'UNIT', 'NORMAL_LOW', 'NORMAL_HIGH', 'RESULT_FLAG']

Data Types:
SUBJECT_ID      object
VISIT           object
VISIT_DATE      object
TEST_NAME       object
RESULT         float64
UNIT            object
NORMAL_LOW     float64
NORMAL_HIGH    float64
RESULT_FLAG     object
dtype: object

Missing Values:
SUBJECT_ID      0
VISIT           0
VISIT_DATE      0
TEST_NAME       0
RESULT         27
UNIT            0
NORMAL_LOW      0
NORMAL_HIGH     0
RESULT_FLAG     0
dtype: int64

In [7]:
# Standardize column names

for name, df in datasets.items():
    
    df.columns = (
        df.columns
        .str.strip()
        .str.upper()
        .str.replace(" ", "_")
    )

print("Column names standardized successfully.")

Column names standardized successfully.

In [8]:
# Remove unnecessary spaces from text columns

for name, df in datasets.items():
    
    text_columns = df.select_dtypes(include="object").columns
    
    for column in text_columns:
        df[column] = df[column].str.strip()

print("Text values cleaned successfully.")

Text values cleaned successfully.

In [9]:
# Check duplicate records

for name, df in datasets.items():
    
    duplicate_count = df.duplicated().sum()
    
    print(f"{name}: {duplicate_count} duplicate record(s)")

Demographics: 0 duplicate record(s)
Vitals: 0 duplicate record(s)
Adverse Events: 0 duplicate record(s)
Lab Results: 0 duplicate record(s)

In [10]:
# Add duplicate flags

demographics["DUPLICATE_FLAG"] = demographics.duplicated(
    subset=["SUBJECT_ID"],
    keep=False
)

vitals["DUPLICATE_FLAG"] = vitals.duplicated(
    keep=False
)

adverse_events["DUPLICATE_FLAG"] = adverse_events.duplicated(
    keep=False
)

lab_results["DUPLICATE_FLAG"] = lab_results.duplicated(
    keep=False
)

print("Duplicate flags created.")

Duplicate flags created.

In [11]:
# Display duplicate records if they exist

print("DEMOGRAPHICS DUPLICATES")
display(
    demographics[
        demographics["DUPLICATE_FLAG"] == True
    ]
)

print("\nVITALS DUPLICATES")
display(
    vitals[
        vitals["DUPLICATE_FLAG"] == True
    ]
)

print("\nADVERSE EVENTS DUPLICATES")
display(
    adverse_events[
        adverse_events["DUPLICATE_FLAG"] == True
    ]
)

print("\nLAB RESULTS DUPLICATES")
display(
    lab_results[
        lab_results["DUPLICATE_FLAG"] == True
    ]
)

DEMOGRAPHICS DUPLICATES

Empty DataFrame
Columns: [SUBJECT_ID, SITE_ID, ENROLL_DATE, AGE, SEX, ARM, AGE_FLAG, DUPLICATE_FLAG]
Index: []

VITALS DUPLICATES

Empty DataFrame
Columns: [SUBJECT_ID, VISIT, VISIT_DATE, SYSTOLIC_BP, DIASTOLIC_BP, HEART_RATE, TEMP_C, WEIGHT_KG, BP_FLAG, TEMP_FLAG, ENROLL_DATE, VISIT_BEFORE_ENROLL_FLAG, DUPLICATE_FLAG]
Index: []

ADVERSE EVENTS DUPLICATES

Empty DataFrame
Columns: [AE_ID, SUBJECT_ID, AE_TERM, START_DATE, END_DATE, SEVERITY, RELATEDNESS, OUTCOME, MISSING_START_FLAG, MISSING_SEVERITY_FLAG, DATE_LOGIC_FLAG, DUPLICATE_FLAG]
Index: []

LAB RESULTS DUPLICATES

Empty DataFrame
Columns: [SUBJECT_ID, VISIT, VISIT_DATE, TEST_NAME, RESULT, UNIT, NORMAL_LOW, NORMAL_HIGH, RESULT_FLAG, DUPLICATE_FLAG]
Index: []

In [13]:
# Convert demographic age to numeric

demographics["AGE"] = pd.to_numeric(
    demographics["AGE"],
    errors="coerce"
)


# Convert vital sign columns to numeric

numeric_vital_columns = [
    "SYSTOLIC_BP",
    "DIASTOLIC_BP",
    "PULSE",
    "TEMP_C"
]

for column in numeric_vital_columns:
    
    numeric_vital_columns = [
        "SYSTOLIC_BP",
        "DIASTOLIC_BP",
        "HEART_RATE",
        "TEMP_C"
    ]

    for column in numeric_vital_columns:
        vitals[column] = pd.to_numeric(
            vitals[column],
            errors="coerce"
        )


# Convert lab result to numeric

lab_results["RESULT_NUMERIC"] = pd.to_numeric(
    lab_results["RESULT"],
    errors="coerce"
)

print("Numeric conversion completed.")

Numeric conversion completed.

In [14]:
# Convert date columns to datetime

demographics["ENROLL_DATE"] = pd.to_datetime(
    demographics["ENROLL_DATE"],
    errors="coerce"
)

vitals["VISIT_DATE"] = pd.to_datetime(
    vitals["VISIT_DATE"],
    errors="coerce"
)

adverse_events["START_DATE"] = pd.to_datetime(
    adverse_events["START_DATE"],
    errors="coerce"
)

adverse_events["END_DATE"] = pd.to_datetime(
    adverse_events["END_DATE"],
    errors="coerce"
)

lab_results["VISIT_DATE"] = pd.to_datetime(
    lab_results["VISIT_DATE"],
    errors="coerce"
)

print("Date conversion completed.")

Date conversion completed.

C:\Users\User\AppData\Local\Temp\ipykernel_10496\4285475165.py:8: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  vitals["VISIT_DATE"] = pd.to_datetime(
C:\Users\User\AppData\Local\Temp\ipykernel_10496\4285475165.py:18: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  adverse_events["END_DATE"] = pd.to_datetime(

In [15]:
# Missing value summary after cleaning

for name, df in datasets.items():
    
    missing_values = df.isnull().sum()
    
    missing_values = missing_values[
        missing_values > 0
    ]
    
    print("\n" + "=" * 50)
    print(name.upper())
    print("=" * 50)
    
    if len(missing_values) == 0:
        print("No missing values found.")
    else:
        print(missing_values)

==================================================
DEMOGRAPHICS
==================================================
ENROLL_DATE    29
AGE             3
dtype: int64

==================================================
VITALS
==================================================
DIASTOLIC_BP    6
dtype: int64

==================================================
ADVERSE EVENTS
==================================================
START_DATE    29
SEVERITY       2
dtype: int64

==================================================
LAB RESULTS
==================================================
VISIT_DATE        650
RESULT             27
RESULT_NUMERIC     27
dtype: int64

In [16]:
# Standardize text values

demographics["SEX"] = (
    demographics["SEX"]
    .str.upper()
    .replace({
        "MALE": "M",
        "FEMALE": "F"
    })
)

adverse_events["SEVERITY"] = (
    adverse_events["SEVERITY"]
    .str.upper()
)

print("Important text values standardized.")

Important text values standardized.

In [17]:
# Check for missing age

demographics["DQ_AGE_MISSING"] = demographics["AGE"].isna()


# Check for age outside the expected range

demographics["DQ_AGE_RANGE"] = (
    demographics["AGE"].notna()
    &
    ~demographics["AGE"].between(18, 100)
)


print("Age validation completed.")

Age validation completed.

In [18]:
# Display age-related data quality issues

age_issues = demographics[
    (demographics["DQ_AGE_MISSING"] == True)
    |
    (demographics["DQ_AGE_RANGE"] == True)
]

display(age_issues)

,SUBJECT_ID,SITE_ID,ENROLL_DATE,AGE,SEX,ARM,AGE_FLAG,DUPLICATE_FLAG,DQ_AGE_MISSING,DQ_AGE_RANGE
0,SUB-001,SITE-01,2025-12-01,5.0,M,Treatment A,OUT_OF_RANGE,False,False,True
17,SUB-018,SITE-03,2025-06-04,NaN,M,Placebo,MISSING,False,True,False
23,SUB-024,SITE-03,NaT,5.0,M,Placebo,OUT_OF_RANGE,False,False,True
34,SUB-035,SITE-03,NaT,NaN,F,Treatment A,MISSING,False,True,False
46,SUB-047,SITE-02,2025-07-07,5.0,F,Treatment B,OUT_OF_RANGE,False,False,True
51,SUB-052,SITE-01,2025-05-03,NaN,M,Treatment A,MISSING,False,True,False

In [19]:
# Check for invalid sex values

demographics["DQ_SEX_INVALID"] = (
    demographics["SEX"].notna()
    &
    ~demographics["SEX"].isin(["M", "F"])
)


print("Sex validation completed.")

Sex validation completed.

In [20]:
# Flag missing enrollment dates

demographics["DQ_ENROLL_DATE_MISSING"] = (
    demographics["ENROLL_DATE"].isna()
)

print("Enrollment date validation completed.")

Enrollment date validation completed.

In [22]:
# Flag missing vital sign values

vitals["DQ_SYSTOLIC_MISSING"] = (
    vitals["SYSTOLIC_BP"].isna()
)

vitals["DQ_DIASTOLIC_MISSING"] = (
    vitals["DIASTOLIC_BP"].isna()
)

vitals["DQ_HEART_RATE_MISSING"] = (
    vitals["HEART_RATE"].isna()
)

vitals["DQ_TEMP_MISSING"] = (
    vitals["TEMP_C"].isna()
)


print("Missing vital sign checks completed.")

Missing vital sign checks completed.

In [23]:
# Check systolic blood pressure range

vitals["DQ_SYSTOLIC_RANGE"] = (
    vitals["SYSTOLIC_BP"].notna()
    &
    ~vitals["SYSTOLIC_BP"].between(70, 250)
)

print("Systolic BP validation completed.")

Systolic BP validation completed.

In [24]:
# Check diastolic blood pressure range

vitals["DQ_DIASTOLIC_RANGE"] = (
    vitals["DIASTOLIC_BP"].notna()
    &
    ~vitals["DIASTOLIC_BP"].between(40, 150)
)

print("Diastolic BP validation completed.")

Diastolic BP validation completed.

In [26]:
# Check pulse range

vitals["DQ_PULSE_RANGE"] = (
    vitals["HEART_RATE"].notna()
    &
    ~vitals["HEART_RATE"].between(30, 220)
)

print("Pulse validation completed.")

Pulse validation completed.

In [27]:
# Check temperature range

vitals["DQ_TEMP_RANGE"] = (
    vitals["TEMP_C"].notna()
    &
    ~vitals["TEMP_C"].between(34, 42)
)

print("Temperature validation completed.")

Temperature validation completed.

In [28]:
# Check blood pressure logic

vitals["DQ_BP_LOGIC"] = (
    vitals["SYSTOLIC_BP"].notna()
    &
    vitals["DIASTOLIC_BP"].notna()
    &
    (
        vitals["DIASTOLIC_BP"]
        >=
        vitals["SYSTOLIC_BP"]
    )
)

print("Blood pressure logic check completed.")

Blood pressure logic check completed.

In [30]:
# Create a combined filter for vital sign issues

vital_issues = vitals[
    (
        vitals["DQ_SYSTOLIC_MISSING"]
        |
        vitals["DQ_DIASTOLIC_MISSING"]
        |
        vitals["DQ_HEART_RATE_MISSING"]
        |
        vitals["DQ_TEMP_MISSING"]
        |
        vitals["DQ_SYSTOLIC_RANGE"]
        |
        vitals["DQ_DIASTOLIC_RANGE"]
        |
        vitals["DQ_PULSE_RANGE"]
        |
        vitals["DQ_TEMP_RANGE"]
        |
        vitals["DQ_BP_LOGIC"]
    )
]

display(vital_issues)

,SUBJECT_ID,VISIT,VISIT_DATE,SYSTOLIC_BP,DIASTOLIC_BP,HEART_RATE,TEMP_C,WEIGHT_KG,BP_FLAG,TEMP_FLAG,ENROLL_DATE,VISIT_BEFORE_ENROLL_FLAG,DUPLICATE_FLAG,DQ_SYSTOLIC_MISSING,DQ_DIASTOLIC_MISSING,DQ_HEART_RATE_MISSING,DQ_TEMP_MISSING,DQ_SYSTOLIC_RANGE,DQ_DIASTOLIC_RANGE,DQ_PULSE_RANGE,DQ_TEMP_RANGE,DQ_BP_LOGIC
1,SUB-001,Week 4,2025-03-11,140,77.0,84,42.5,63.6,OK,OUT_OF_RANGE,12-01-2025,OK,False,False,False,False,False,False,False,False,True,False
10,SUB-003,Week 12,2025-09-24,260,77.0,74,37.5,69.5,OUT_OF_RANGE,OK,06-06-2025,OK,False,False,False,False,False,True,False,False,False,False
13,SUB-004,Week 4,2025-03-28,260,69.0,68,36.8,65.5,OUT_OF_RANGE,OK,29-01-2025,OK,False,False,False,False,False,True,False,False,False,False
16,SUB-005,Screening,2025-05-27,125,89.0,57,42.5,75.4,OK,OUT_OF_RANGE,29-05-2025,QUERY,False,False,False,False,False,False,False,False,True,False
22,SUB-006,Baseline,2025-04-01,260,70.0,73,36.9,75.6,OUT_OF_RANGE,OK,03-03-2025,OK,False,False,False,False,False,True,False,False,False,False
25,SUB-006,Week 12,2025-06-22,260,82.0,73,36.5,52.3,OUT_OF_RANGE,OK,03-03-2025,OK,False,False,False,False,False,True,False,False,False,False
39,SUB-009,Week 12,2025-11-10,115,89.0,66,42.5,82.1,OK,OUT_OF_RANGE,20-07-2025,OK,False,False,False,False,False,False,False,False,True,False
48,SUB-011,Week 8,2025-09-03,110,NaN,81,37.0,71.7,MISSING,OK,09-06-2025,OK,False,False,True,False,False,False,False,False,False,False
63,SUB-015,Screening,2025-01-17,260,85.0,75,37.5,61.5,OUT_OF_RANGE,OK,17-01-2025,OK,False,False,False,False,False,True,False,False,False,False
77,SUB-017,Week 12,2025-08-21,131,81.0,64,42.5,58.2,OK,OUT_OF_RANGE,02-05-2025,OK,False,False,False,False,False,False,False,False,True,False
84,SUB-019,Baseline,2025-07-31,260,69.0,57,36.9,62.2,OUT_OF_RANGE,OK,04-07-2025,OK,False,False,False,False,False,True,False,False,False,False
90,SUB-020,Week 4,2025-07-17,125,NaN,71,36.5,64.5,MISSING,OK,22-05-2025,OK,False,False,True,False,False,False,False,False,False,False
96,SUB-021,Week 12,2025-08-05,133,NaN,79,37.2,39.9,MISSING,OK,13-04-2025,OK,False,False,True,False,False,False,False,False,False,False
117,SUB-026,Week 4,2025-04-07,118,53.0,73,42.5,81.1,OK,OUT_OF_RANGE,11-02-2025,OK,False,False,False,False,False,False,False,False,True,False
143,SUB-032,Screening,2025-04-09,100,NaN,71,36.8,80.1,MISSING,OK,14-04-2025,QUERY,False,False,True,False,False,False,False,False,False,False
144,SUB-032,Baseline,2025-05-12,260,65.0,77,37.0,79.3,OUT_OF_RANGE,OK,14-04-2025,OK,False,False,False,False,False,True,False,False,False,False
159,SUB-035,Baseline,2025-08-20,260,70.0,78,36.6,80.2,OUT_OF_RANGE,OK,21-07-2025,OK,False,False,False,False,False,True,False,False,False,False
166,SUB-036,Week 8,2025-07-20,133,82.0,84,42.5,90.0,OK,OUT_OF_RANGE,27-04-2025,OK,False,False,False,False,False,False,False,False,True,False
169,SUB-037,Baseline,2025-08-06,122,65.0,81,42.5,100.1,OK,OUT_OF_RANGE,09-07-2025,OK,False,False,False,False,False,False,False,False,True,False
190,SUB-041,Week 12,2025-09-30,140,79.0,94,42.5,94.6,OK,OUT_OF_RANGE,08-06-2025,OK,False,False,False,False,False,False,False,False,True,False
203,SUB-044,Week 4,2025-03-23,260,63.0,69,37.3,83.1,OUT_OF_RANGE,OK,27-01-2025,OK,False,False,False,False,False,True,False,False,False,False
205,SUB-044,Week 12,2025-05-20,128,NaN,76,36.7,69.4,MISSING,OK,27-01-2025,OK,False,False,True,False,False,False,False,False,False,False
208,SUB-045,Week 4,2025-04-05,135,NaN,94,36.8,86.4,MISSING,OK,07-02-2025,OK,False,False,True,False,False,False,False,False,False,False
209,SUB-045,Week 8,2025-05-03,260,83.0,63,36.6,96.9,OUT_OF_RANGE,OK,07-02-2025,OK,False,False,False,False,False,True,False,False,False,False
211,SUB-046,Screening,2025-03-16,260,99.0,73,36.9,85.7,OUT_OF_RANGE,OK,14-03-2025,OK,False,False,False,False,False,True,False,False,False,False
220,SUB-048,Screening,2025-04-28,87,98.0,60,36.3,85.3,OK,OK,28-04-2025,OK,False,False,False,False,False,False,False,False,False,True
228,SUB-049,Week 12,2025-06-22,260,74.0,75,37.0,72.6,OUT_OF_RANGE,OK,04-03-2025,OK,False,False,False,False,False,True,False,False,False,False
234,SUB-051,Screening,2025-01-08,260,65.0,73,37.6,61.6,OUT_OF_RANGE,OK,07-01-2025,OK,False,False,False,False,False,True,False,False,False,False
252,SUB-054,Week 12,2025-06-22,260,82.0,73,36.9,72.8,OUT_OF_RANGE,OK,01-03-2025,OK,False,False,False,False,False,True,False,False,False,False
273,SUB-059,Baseline,2025-02-19,94,96.0,62,36.7,68.4,OK,OK,21-01-2025,OK,False,False,False,False,False,False,False,False,False,True

In [31]:
# Add enrollment date to vital signs data

vitals = vitals.merge(
    demographics[
        ["SUBJECT_ID", "ENROLL_DATE"]
    ],
    on="SUBJECT_ID",
    how="left"
)

print("Enrollment date added to vital signs data.")

display(vitals.head())

Enrollment date added to vital signs data.

,SUBJECT_ID,VISIT,VISIT_DATE,SYSTOLIC_BP,DIASTOLIC_BP,HEART_RATE,TEMP_C,WEIGHT_KG,BP_FLAG,TEMP_FLAG,ENROLL_DATE_x,VISIT_BEFORE_ENROLL_FLAG,DUPLICATE_FLAG,DQ_SYSTOLIC_MISSING,DQ_DIASTOLIC_MISSING,DQ_HEART_RATE_MISSING,DQ_TEMP_MISSING,DQ_SYSTOLIC_RANGE,DQ_DIASTOLIC_RANGE,DQ_PULSE_RANGE,DQ_TEMP_RANGE,DQ_BP_LOGIC,ENROLL_DATE_y
0,SUB-001,Screening,2025-01-13,115,76.0,62,36.4,82.6,OK,OK,12-01-2025,OK,False,False,False,False,False,False,False,False,False,False,2025-12-01
1,SUB-001,Week 4,2025-03-11,140,77.0,84,42.5,63.6,OK,OUT_OF_RANGE,12-01-2025,OK,False,False,False,False,False,False,False,False,True,False,2025-12-01
2,SUB-001,Week 8,2025-04-05,127,91.0,73,37.3,37.9,OK,OK,12-01-2025,OK,False,False,False,False,False,False,False,False,False,False,2025-12-01
3,SUB-002,Screening,2025-02-11,133,78.0,71,36.8,46.2,OK,OK,10-02-2025,OK,False,False,False,False,False,False,False,False,False,False,2025-10-02
4,SUB-002,Baseline,2025-03-12,118,81.0,88,36.6,61.5,OK,OK,10-02-2025,OK,False,False,False,False,False,False,False,False,False,False,2025-10-02

In [33]:
# Check for missing visit dates

vitals["DQ_VISIT_DATE_MISSING"] = (
    vitals["VISIT_DATE"].isna()
)


# Check if visit happened before enrollment

vitals["DQ_VISIT_BEFORE_ENROLL"] = (
    vitals["VISIT_DATE"].notna()
    &
    vitals["ENROLL_DATE_y"].notna()
    &
    (
        vitals["VISIT_DATE"]
        <
        vitals["ENROLL_DATE_y"]
    )
)

print("Visit date validation completed.")

Visit date validation completed.

In [35]:
# Display records with visit date issues

visit_date_issues = vitals[
    vitals["DQ_VISIT_DATE_MISSING"]
    |
    vitals["DQ_VISIT_BEFORE_ENROLL"]
]

display(
    visit_date_issues[
        [
            "SUBJECT_ID",
            "VISIT_DATE",
            "ENROLL_DATE_y",
            "DQ_VISIT_DATE_MISSING",
            "DQ_VISIT_BEFORE_ENROLL"
        ]
    ]
)

,SUBJECT_ID,VISIT_DATE,ENROLL_DATE_y,DQ_VISIT_DATE_MISSING,DQ_VISIT_BEFORE_ENROLL
0,SUB-001,2025-01-13,2025-12-01,False,True
1,SUB-001,2025-03-11,2025-12-01,False,True
2,SUB-001,2025-04-05,2025-12-01,False,True
3,SUB-002,2025-02-11,2025-10-02,False,True
4,SUB-002,2025-03-12,2025-10-02,False,True
...,...,...,...,...,...
268,SUB-058,2025-08-07,2025-11-07,False,True
269,SUB-058,2025-09-06,2025-11-07,False,True
270,SUB-058,2025-10-03,2025-11-07,False,True
271,SUB-058,2025-10-31,2025-11-07,False,True
277,SUB-060,2025-02-01,2025-02-02,False,True

In [36]:
# Flag missing adverse event terms

adverse_events["DQ_AE_TERM_MISSING"] = (
    adverse_events["AE_TERM"].isna()
)

print("AE term validation completed.")

AE term validation completed.

In [37]:
# Flag missing adverse event start dates

adverse_events["DQ_START_DATE_MISSING"] = (
    adverse_events["START_DATE"].isna()
)

print("AE start date validation completed.")

AE start date validation completed.

In [38]:
# Flag missing severity

adverse_events["DQ_SEVERITY_MISSING"] = (
    adverse_events["SEVERITY"].isna()
)

print("AE severity missing check completed.")

AE severity missing check completed.

In [39]:
# Flag invalid severity values

adverse_events["DQ_SEVERITY_INVALID"] = (
    adverse_events["SEVERITY"].notna()
    &
    ~adverse_events["SEVERITY"].isin(
        ["MILD", "MODERATE", "SEVERE"]
    )
)

print("AE severity validation completed.")

AE severity validation completed.

In [40]:
# Check adverse event date logic

adverse_events["DQ_DATE_LOGIC"] = (
    adverse_events["START_DATE"].notna()
    &
    adverse_events["END_DATE"].notna()
    &
    (
        adverse_events["END_DATE"]
        <
        adverse_events["START_DATE"]
    )
)

print("AE date logic validation completed.")

AE date logic validation completed.

In [41]:
# Display adverse event records with data quality issues

ae_issues = adverse_events[
    adverse_events["DQ_AE_TERM_MISSING"]
    |
    adverse_events["DQ_START_DATE_MISSING"]
    |
    adverse_events["DQ_SEVERITY_MISSING"]
    |
    adverse_events["DQ_SEVERITY_INVALID"]
    |
    adverse_events["DQ_DATE_LOGIC"]
]

display(ae_issues)

,AE_ID,SUBJECT_ID,AE_TERM,START_DATE,END_DATE,SEVERITY,RELATEDNESS,OUTCOME,MISSING_START_FLAG,MISSING_SEVERITY_FLAG,DATE_LOGIC_FLAG,DUPLICATE_FLAG,DQ_AE_TERM_MISSING,DQ_START_DATE_MISSING,DQ_SEVERITY_MISSING,DQ_SEVERITY_INVALID,DQ_DATE_LOGIC
0,AE-0001,SUB-001,Injection site reaction,2025-04-02,2025-02-18,MILD,Not Related,Resolved,OK,OK,OK,False,False,False,False,False,True
1,AE-0002,SUB-001,Rash,NaT,2025-01-18,MODERATE,Not Related,Resolved,OK,OK,OK,False,False,True,False,False,False
2,AE-0003,SUB-004,Injection site reaction,NaT,2025-03-05,MODERATE,Related,Ongoing,OK,OK,OK,False,False,True,False,False,False
4,AE-0005,SUB-005,Diarrhea,NaT,2025-08-09,MODERATE,Not Related,Resolved,OK,OK,OK,False,False,True,False,False,False
6,AE-0007,SUB-007,Rash,2025-10-04,2025-04-29,MILD,Possibly Related,Ongoing,OK,OK,OK,False,False,False,False,False,True
7,AE-0008,SUB-011,Upper respiratory infection,NaT,2025-07-25,MODERATE,Possibly Related,Ongoing,OK,OK,OK,False,False,True,False,False,False
8,AE-0009,SUB-011,Back pain,2025-08-07,2025-07-16,MILD,Related,Resolved with sequelae,OK,OK,OK,False,False,False,False,False,True
9,AE-0010,SUB-012,Back pain,NaT,2025-08-10,SEVERE,Related,Resolving,OK,OK,OK,False,False,True,False,False,False
10,AE-0011,SUB-013,Back pain,NaT,2025-08-10,SEVERE,Related,Ongoing,OK,OK,OK,False,False,True,False,False,False
11,AE-0012,SUB-013,Dizziness,NaT,2025-07-11,SEVERE,Related,Resolving,OK,OK,OK,False,False,True,False,False,False
12,AE-0013,SUB-014,Insomnia,2025-02-09,2025-09-21,NaN,Possibly Related,Resolved,OK,QUERY,OK,False,False,False,True,False,False
15,AE-0016,SUB-018,Insomnia,NaT,2025-05-01,MILD,Not Related,Ongoing,OK,OK,OK,False,False,True,False,False,False
16,AE-0017,SUB-019,Fatigue,NaT,2025-09-03,MODERATE,Not Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False
17,AE-0018,SUB-020,Headache,NaT,2025-08-26,MILD,Possibly Related,Resolving,OK,OK,OK,False,False,True,False,False,False
18,AE-0019,SUB-021,Dizziness,NaT,2025-07-20,MODERATE,Possibly Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False
20,AE-0021,SUB-022,Upper respiratory infection,NaT,2025-10-07,SEVERE,Related,Resolved,QUERY,OK,OK,False,False,True,False,False,False
21,AE-0022,SUB-023,Headache,2025-11-04,2025-04-13,MILD,Not Related,Resolved,OK,OK,OK,False,False,False,False,False,True
23,AE-0024,SUB-026,Fatigue,NaT,2025-03-24,MILD,Not Related,Resolving,OK,OK,OK,False,False,True,False,False,False
25,AE-0026,SUB-026,Dizziness,NaT,2025-04-07,MODERATE,Not Related,Resolving,OK,OK,OK,False,False,True,False,False,False
26,AE-0027,SUB-027,Insomnia,NaT,2025-08-28,MODERATE,Possibly Related,Resolved,OK,OK,OK,False,False,True,False,False,False
27,AE-0028,SUB-029,Back pain,NaT,2025-03-11,MILD,Possibly Related,Ongoing,OK,OK,QUERY,False,False,True,False,False,False
28,AE-0029,SUB-031,Dizziness,NaT,2025-10-07,MILD,Not Related,Ongoing,OK,OK,OK,False,False,True,False,False,False
30,AE-0031,SUB-031,Upper respiratory infection,NaT,2025-08-03,SEVERE,Possibly Related,Resolved,OK,OK,OK,False,False,True,False,False,False
31,AE-0032,SUB-031,Diarrhea,NaT,2025-10-05,MODERATE,Possibly Related,Resolving,OK,OK,OK,False,False,True,False,False,False
32,AE-0033,SUB-032,Diarrhea,NaT,2025-06-02,MODERATE,Not Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False
33,AE-0034,SUB-033,Injection site reaction,NaT,2025-06-29,MODERATE,Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False
35,AE-0036,SUB-036,Rash,NaT,2025-07-18,SEVERE,Not Related,Ongoing,OK,OK,OK,False,False,True,False,False,False
37,AE-0038,SUB-043,Insomnia,NaT,2025-04-15,SEVERE,Related,Resolved,OK,OK,OK,False,False,True,False,False,False
38,AE-0039,SUB-044,Upper respiratory infection,NaT,2025-02-22,MILD,Related,Resolving,OK,OK,OK,False,False,True,False,False,False
39,AE-0040,SUB-045,Injection site reaction,2025-10-04,2025-04-26,NaN,Possibly Related,Resolved,OK,QUERY,OK,False,False,False,True,False,True
40,AE-0041,SUB-046,Dizziness,NaT,2025-06-01,MILD,Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False
41,AE-0042,SUB-047,Rash,NaT,2025-10-12,MODERATE,Not Related,Ongoing,OK,OK,OK,False,False,True,False,False,False
42,AE-0043,SUB-048,Headache,2025-10-07,2025-07-18,SEVERE,Not Related,Resolving,OK,OK,OK,False,False,False,False,False,True
43,AE-0044,SUB-050,Nausea,NaT,2025-06-30,MODERATE,Possibly Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False
44,AE-0045,SUB-051,Headache,2025-12-03,2025-03-26,SEVERE,Possibly Related,Ongoing,OK,OK,OK,False,False,False,False,False,True
45,AE-0046,SUB-052,Back pain,2025-04-04,2025-04-01,SEVERE,Not Related,Resolved with sequelae,OK,OK,QUERY,False,False,False,False,False,True
46,AE-0047,SUB-053,Insomnia,2025-07-04,2025-04-09,MILD,Related,Ongoing,OK,OK,OK,False,False,False,False,False,True
47,AE-0048,SUB-054,Diarrhea,2025-11-03,2025-03-21,MILD,Possibly Related,Resolving,OK,OK,OK,False,False,False,False,False,True
48,AE-0049,SUB-054,Dizziness,NaT,2025-04-25,SEVERE,Possibly Related,Resolved,OK,OK,OK,False,False,True,False,False,False
49,AE-0050,SUB-054,Rash,2025-11-03,2025-03-08,SEVERE,Not Related,Resolved with sequelae,OK,OK,QUERY,False,False,False,False,False,True
50,AE-0051,SUB-059,Upper respiratory infection,NaT,2025-03-04,SEVERE,Not Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False

In [42]:
# Flag missing laboratory results

lab_results["DQ_RESULT_MISSING"] = (
    lab_results["RESULT"].isna()
)

print("Lab result missing check completed.")

Lab result missing check completed.

In [43]:
# Flag invalid non-numeric laboratory results

lab_results["DQ_RESULT_INVALID"] = (
    lab_results["RESULT"].notna()
    &
    lab_results["RESULT_NUMERIC"].isna()
)

print("Lab result validation completed.")

Lab result validation completed.

In [44]:
# Flag missing laboratory units

lab_results["DQ_UNIT_MISSING"] = (
    lab_results["UNIT"].isna()
)

print("Lab unit validation completed.")

Lab unit validation completed.

In [45]:
# Create default clinical flag

lab_results["CLINICAL_FLAG"] = "NORMAL"


# Identify records with valid result and reference range

valid_lab_range = (
    lab_results["RESULT_NUMERIC"].notna()
    &
    lab_results["NORMAL_LOW"].notna()
    &
    lab_results["NORMAL_HIGH"].notna()
)


# Flag low results

lab_results.loc[
    valid_lab_range
    &
    (
        lab_results["RESULT_NUMERIC"]
        <
        lab_results["NORMAL_LOW"]
    ),
    "CLINICAL_FLAG"
] = "LOW"


# Flag high results

lab_results.loc[
    valid_lab_range
    &
    (
        lab_results["RESULT_NUMERIC"]
        >
        lab_results["NORMAL_HIGH"]
    ),
    "CLINICAL_FLAG"
] = "HIGH"


print("Clinical lab flags created.")

Clinical lab flags created.

In [46]:
# Show data quality issues

lab_data_issues = lab_results[
    lab_results["DQ_RESULT_MISSING"]
    |
    lab_results["DQ_RESULT_INVALID"]
    |
    lab_results["DQ_UNIT_MISSING"]
]

print("LAB DATA QUALITY ISSUES")
display(lab_data_issues)


# Show clinical abnormalities separately

lab_clinical_review = lab_results[
    lab_results["CLINICAL_FLAG"].isin(
        ["LOW", "HIGH"]
    )
]

print("CLINICALLY ABNORMAL RESULTS")
display(lab_clinical_review)

LAB DATA QUALITY ISSUES

,SUBJECT_ID,VISIT,VISIT_DATE,TEST_NAME,RESULT,UNIT,NORMAL_LOW,NORMAL_HIGH,RESULT_FLAG,DUPLICATE_FLAG,RESULT_NUMERIC,DQ_RESULT_MISSING,DQ_RESULT_INVALID,DQ_UNIT_MISSING,CLINICAL_FLAG
10,SUB-001,Week 8,2025-06-04,ALT,NaN,U/L,7.0,56.0,MISSING,False,NaN,True,False,False,NORMAL
21,SUB-002,Baseline,2025-10-03,AST,NaN,U/L,8.0,48.0,MISSING,False,NaN,True,False,False,NORMAL
148,SUB-008,Week 8,NaT,WBC,NaN,10^9/L,4.0,11.0,MISSING,False,NaN,True,False,False,NORMAL
187,SUB-010,Week 12,2025-03-08,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL
222,SUB-012,Week 12,2025-12-09,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL
223,SUB-012,Week 12,2025-12-09,WBC,NaN,10^9/L,4.0,11.0,MISSING,False,NaN,True,False,False,NORMAL
348,SUB-019,Week 12,NaT,WBC,NaN,10^9/L,4.0,11.0,MISSING,False,NaN,True,False,False,NORMAL
358,SUB-020,Week 4,NaT,WBC,NaN,10^9/L,4.0,11.0,MISSING,False,NaN,True,False,False,NORMAL
372,SUB-021,Baseline,2025-11-05,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL
468,SUB-026,Week 4,2025-08-04,WBC,NaN,10^9/L,4.0,11.0,MISSING,False,NaN,True,False,False,NORMAL
505,SUB-028,Week 8,NaT,ALT,NaN,U/L,7.0,56.0,MISSING,False,NaN,True,False,False,NORMAL
515,SUB-029,Week 4,2025-07-04,ALT,NaN,U/L,7.0,56.0,MISSING,False,NaN,True,False,False,NORMAL
517,SUB-029,Week 4,2025-07-04,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL
538,SUB-030,Week 4,NaT,WBC,NaN,10^9/L,4.0,11.0,MISSING,False,NaN,True,False,False,NORMAL
567,SUB-032,Baseline,2025-12-05,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL
576,SUB-032,Week 8,2025-07-07,AST,NaN,U/L,8.0,48.0,MISSING,False,NaN,True,False,False,NORMAL
586,SUB-033,Baseline,NaT,AST,NaN,U/L,8.0,48.0,MISSING,False,NaN,True,False,False,NORMAL
597,SUB-033,Week 8,NaT,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL
662,SUB-036,Week 12,NaT,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL
682,SUB-038,Baseline,2025-12-06,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL
776,SUB-043,Week 4,NaT,AST,NaN,U/L,8.0,48.0,MISSING,False,NaN,True,False,False,NORMAL
800,SUB-044,Week 12,NaT,ALT,NaN,U/L,7.0,56.0,MISSING,False,NaN,True,False,False,NORMAL
845,SUB-047,Week 8,NaT,ALT,NaN,U/L,7.0,56.0,MISSING,False,NaN,True,False,False,NORMAL
854,SUB-047,Week 12,NaT,Creatinine,NaN,mg/dL,0.6,1.3,MISSING,False,NaN,True,False,False,NORMAL
899,SUB-050,Baseline,2025-03-07,Creatinine,NaN,mg/dL,0.6,1.3,MISSING,False,NaN,True,False,False,NORMAL
1045,SUB-058,Week 4,2025-05-09,ALT,NaN,U/L,7.0,56.0,MISSING,False,NaN,True,False,False,NORMAL
1072,SUB-059,Week 8,NaT,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL

CLINICALLY ABNORMAL RESULTS

,SUBJECT_ID,VISIT,VISIT_DATE,TEST_NAME,RESULT,UNIT,NORMAL_LOW,NORMAL_HIGH,RESULT_FLAG,DUPLICATE_FLAG,RESULT_NUMERIC,DQ_RESULT_MISSING,DQ_RESULT_INVALID,DQ_UNIT_MISSING,CLINICAL_FLAG
20,SUB-002,Baseline,2025-10-03,ALT,61.08,U/L,7.0,56.0,OUT_OF_RANGE,False,61.08,False,False,False,HIGH
30,SUB-002,Week 8,2025-05-05,ALT,64.12,U/L,7.0,56.0,OUT_OF_RANGE,False,64.12,False,False,False,HIGH
35,SUB-002,Week 12,2025-02-06,ALT,168.00,U/L,7.0,56.0,OUT_OF_RANGE,False,168.00,False,False,False,HIGH
40,SUB-003,Baseline,2025-04-07,ALT,56.12,U/L,7.0,56.0,OUT_OF_RANGE,False,56.12,False,False,False,HIGH
67,SUB-004,Week 4,NaT,Hemoglobin,52.50,g/dL,12.0,17.5,OUT_OF_RANGE,False,52.50,False,False,False,HIGH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1028,SUB-056,Week 8,NaT,WBC,11.19,10^9/L,4.0,11.0,OUT_OF_RANGE,False,11.19,False,False,False,HIGH
1042,SUB-057,Week 12,NaT,Hemoglobin,52.50,g/dL,12.0,17.5,OUT_OF_RANGE,False,52.50,False,False,False,HIGH
1073,SUB-059,Week 8,NaT,WBC,33.00,10^9/L,4.0,11.0,OUT_OF_RANGE,False,33.00,False,False,False,HIGH
1074,SUB-059,Week 8,NaT,Creatinine,3.90,mg/dL,0.6,1.3,OUT_OF_RANGE,False,3.90,False,False,False,HIGH
1075,SUB-059,Week 12,NaT,ALT,168.00,U/L,7.0,56.0,OUT_OF_RANGE,False,168.00,False,False,False,HIGH

In [47]:
# Count duplicate records in each dataset

duplicate_summary = pd.DataFrame({
    "DATASET": [
        "Demographics",
        "Vitals",
        "Adverse Events",
        "Lab Results"
    ],
    "DUPLICATE_RECORDS": [
        demographics["DUPLICATE_FLAG"].sum(),
        vitals["DUPLICATE_FLAG"].sum(),
        adverse_events["DUPLICATE_FLAG"].sum(),
        lab_results["DUPLICATE_FLAG"].sum()
    ]
})

display(duplicate_summary)

          DATASET  DUPLICATE_RECORDS
0    Demographics                  0
1          Vitals                  0
2  Adverse Events                  0
3     Lab Results                  0

In [48]:
# Count data quality issues in each dataset

dq_summary = pd.DataFrame({
    "DATASET": [
        "Demographics",
        "Vitals",
        "Adverse Events",
        "Lab Results"
    ],
    
    "TOTAL_RECORDS": [
        len(demographics),
        len(vitals),
        len(adverse_events),
        len(lab_results)
    ],
    
    "DUPLICATE_ISSUES": [
        demographics["DUPLICATE_FLAG"].sum(),
        vitals["DUPLICATE_FLAG"].sum(),
        adverse_events["DUPLICATE_FLAG"].sum(),
        lab_results["DUPLICATE_FLAG"].sum()
    ]
})

display(dq_summary)

          DATASET  TOTAL_RECORDS  DUPLICATE_ISSUES
0    Demographics             60                 0
1          Vitals            281                 0
2  Adverse Events             51                 0
3     Lab Results           1100                 0

In [49]:
# Count all demographic data quality issues

demographics["TOTAL_DQ_ISSUES"] = (
    demographics["DUPLICATE_FLAG"].astype(int)
    +
    demographics["DQ_AGE_MISSING"].astype(int)
    +
    demographics["DQ_AGE_RANGE"].astype(int)
    +
    demographics["DQ_SEX_INVALID"].astype(int)
    +
    demographics["DQ_ENROLL_DATE_MISSING"].astype(int)
)

display(
    demographics[
        demographics["TOTAL_DQ_ISSUES"] > 0
    ]
)

,SUBJECT_ID,SITE_ID,ENROLL_DATE,AGE,SEX,ARM,AGE_FLAG,DUPLICATE_FLAG,DQ_AGE_MISSING,DQ_AGE_RANGE,DQ_SEX_INVALID,DQ_ENROLL_DATE_MISSING,TOTAL_DQ_ISSUES
0,SUB-001,SITE-01,2025-12-01,5.0,M,Treatment A,OUT_OF_RANGE,False,False,True,False,False,1
3,SUB-004,SITE-01,NaT,73.0,M,Treatment A,OK,False,False,False,False,True,1
4,SUB-005,SITE-01,NaT,48.0,M,Placebo,OK,False,False,False,False,True,1
8,SUB-009,SITE-02,NaT,45.0,F,Treatment A,OK,False,False,False,False,True,1
9,SUB-010,SITE-01,NaT,59.0,M,Treatment B,OK,False,False,False,False,True,1
11,SUB-012,SITE-04,NaT,45.0,M,Treatment B,OK,False,False,False,False,True,1
12,SUB-013,SITE-01,NaT,55.0,F,Placebo,OK,False,False,False,False,True,1
14,SUB-015,SITE-01,NaT,27.0,M,Treatment B,OK,False,False,False,False,True,1
17,SUB-018,SITE-03,2025-06-04,NaN,M,Placebo,MISSING,False,True,False,False,False,1
19,SUB-020,SITE-02,NaT,32.0,M,Treatment A,OK,False,False,False,False,True,1
20,SUB-021,SITE-04,NaT,72.0,F,Placebo,OK,False,False,False,False,True,1
21,SUB-022,SITE-02,NaT,48.0,F,Treatment A,OK,False,False,False,False,True,1
22,SUB-023,SITE-02,NaT,52.0,F,Treatment B,OK,False,False,False,False,True,1
23,SUB-024,SITE-03,NaT,5.0,M,Placebo,OUT_OF_RANGE,False,False,True,False,True,2
26,SUB-027,SITE-02,NaT,35.0,F,Placebo,OK,False,False,False,False,True,1
30,SUB-031,SITE-02,NaT,43.0,F,Placebo,OK,False,False,False,False,True,1
31,SUB-032,SITE-01,NaT,77.0,F,Placebo,OK,False,False,False,False,True,1
32,SUB-033,SITE-04,NaT,51.0,F,Placebo,OK,False,False,False,False,True,1
33,SUB-034,SITE-01,NaT,37.0,M,Placebo,OK,False,False,False,False,True,1
34,SUB-035,SITE-03,NaT,NaN,F,Treatment A,MISSING,False,True,False,False,True,2
35,SUB-036,SITE-03,NaT,34.0,M,Treatment B,OK,False,False,False,False,True,1
37,SUB-038,SITE-02,NaT,24.0,M,Placebo,OK,False,False,False,False,True,1
38,SUB-039,SITE-03,NaT,33.0,M,Treatment A,OK,False,False,False,False,True,1
39,SUB-040,SITE-03,NaT,54.0,M,Placebo,OK,False,False,False,False,True,1
42,SUB-043,SITE-02,NaT,50.0,M,Placebo,OK,False,False,False,False,True,1
43,SUB-044,SITE-01,NaT,47.0,F,Treatment A,OK,False,False,False,False,True,1
45,SUB-046,SITE-02,NaT,41.0,F,Treatment A,OK,False,False,False,False,True,1
46,SUB-047,SITE-02,2025-07-07,5.0,F,Treatment B,OUT_OF_RANGE,False,False,True,False,False,1
47,SUB-048,SITE-03,NaT,66.0,F,Treatment A,OK,False,False,False,False,True,1
51,SUB-052,SITE-01,2025-05-03,NaN,M,Treatment A,MISSING,False,True,False,False,False,1
52,SUB-053,SITE-03,NaT,42.0,M,Treatment B,OK,False,False,False,False,True,1
55,SUB-056,SITE-02,NaT,65.0,M,Placebo,OK,False,False,False,False,True,1
58,SUB-059,SITE-01,NaT,56.0,M,Placebo,OK,False,False,False,False,True,1

In [51]:
# Count all vital sign data quality issues

vitals["TOTAL_DQ_ISSUES"] = (
    vitals["DUPLICATE_FLAG"].astype(int)
    +
    vitals["DQ_SYSTOLIC_MISSING"].astype(int)
    +
    vitals["DQ_DIASTOLIC_MISSING"].astype(int)
    +
    vitals["DQ_HEART_RATE_MISSING"].astype(int)
    +
    vitals["DQ_TEMP_MISSING"].astype(int)
    +
    vitals["DQ_SYSTOLIC_RANGE"].astype(int)
    +
    vitals["DQ_DIASTOLIC_RANGE"].astype(int)
    +
    vitals["DQ_PULSE_RANGE"].astype(int)
    +
    vitals["DQ_TEMP_RANGE"].astype(int)
    +
    vitals["DQ_BP_LOGIC"].astype(int)
    +
    vitals["DQ_VISIT_DATE_MISSING"].astype(int)
    +
    vitals["DQ_VISIT_BEFORE_ENROLL"].astype(int)
)

display(
    vitals[
        vitals["TOTAL_DQ_ISSUES"] > 0
    ]
)

,SUBJECT_ID,VISIT,VISIT_DATE,SYSTOLIC_BP,DIASTOLIC_BP,HEART_RATE,TEMP_C,WEIGHT_KG,BP_FLAG,TEMP_FLAG,ENROLL_DATE_x,VISIT_BEFORE_ENROLL_FLAG,DUPLICATE_FLAG,DQ_SYSTOLIC_MISSING,DQ_DIASTOLIC_MISSING,DQ_HEART_RATE_MISSING,DQ_TEMP_MISSING,DQ_SYSTOLIC_RANGE,DQ_DIASTOLIC_RANGE,DQ_PULSE_RANGE,DQ_TEMP_RANGE,DQ_BP_LOGIC,ENROLL_DATE_y,DQ_VISIT_DATE_MISSING,DQ_VISIT_BEFORE_ENROLL,TOTAL_DQ_ISSUES
0,SUB-001,Screening,2025-01-13,115,76.0,62,36.4,82.6,OK,OK,12-01-2025,OK,False,False,False,False,False,False,False,False,False,False,2025-12-01,False,True,1
1,SUB-001,Week 4,2025-03-11,140,77.0,84,42.5,63.6,OK,OUT_OF_RANGE,12-01-2025,OK,False,False,False,False,False,False,False,False,True,False,2025-12-01,False,True,2
2,SUB-001,Week 8,2025-04-05,127,91.0,73,37.3,37.9,OK,OK,12-01-2025,OK,False,False,False,False,False,False,False,False,False,False,2025-12-01,False,True,1
3,SUB-002,Screening,2025-02-11,133,78.0,71,36.8,46.2,OK,OK,10-02-2025,OK,False,False,False,False,False,False,False,False,False,False,2025-10-02,False,True,1
4,SUB-002,Baseline,2025-03-12,118,81.0,88,36.6,61.5,OK,OK,10-02-2025,OK,False,False,False,False,False,False,False,False,False,False,2025-10-02,False,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,SUB-058,Week 4,2025-09-06,111,65.0,89,36.7,68.7,OK,OK,11-07-2025,OK,False,False,False,False,False,False,False,False,False,False,2025-11-07,False,True,1
270,SUB-058,Week 8,2025-10-03,140,83.0,78,37.4,63.6,OK,OK,11-07-2025,OK,False,False,False,False,False,False,False,False,False,False,2025-11-07,False,True,1
271,SUB-058,Week 12,2025-10-31,134,78.0,76,37.3,78.6,OK,OK,11-07-2025,OK,False,False,False,False,False,False,False,False,False,False,2025-11-07,False,True,1
273,SUB-059,Baseline,2025-02-19,94,96.0,62,36.7,68.4,OK,OK,21-01-2025,OK,False,False,False,False,False,False,False,False,False,True,NaT,False,False,1
277,SUB-060,Screening,2025-02-01,112,73.0,79,37.2,72.3,OK,OK,02-02-2025,QUERY,False,False,False,False,False,False,False,False,False,False,2025-02-02,False,True,1

In [52]:
# Count all adverse event data quality issues

adverse_events["TOTAL_DQ_ISSUES"] = (
    adverse_events["DUPLICATE_FLAG"].astype(int)
    +
    adverse_events["DQ_AE_TERM_MISSING"].astype(int)
    +
    adverse_events["DQ_START_DATE_MISSING"].astype(int)
    +
    adverse_events["DQ_SEVERITY_MISSING"].astype(int)
    +
    adverse_events["DQ_SEVERITY_INVALID"].astype(int)
    +
    adverse_events["DQ_DATE_LOGIC"].astype(int)
)

display(
    adverse_events[
        adverse_events["TOTAL_DQ_ISSUES"] > 0
    ]
)

,AE_ID,SUBJECT_ID,AE_TERM,START_DATE,END_DATE,SEVERITY,RELATEDNESS,OUTCOME,MISSING_START_FLAG,MISSING_SEVERITY_FLAG,DATE_LOGIC_FLAG,DUPLICATE_FLAG,DQ_AE_TERM_MISSING,DQ_START_DATE_MISSING,DQ_SEVERITY_MISSING,DQ_SEVERITY_INVALID,DQ_DATE_LOGIC,TOTAL_DQ_ISSUES
0,AE-0001,SUB-001,Injection site reaction,2025-04-02,2025-02-18,MILD,Not Related,Resolved,OK,OK,OK,False,False,False,False,False,True,1
1,AE-0002,SUB-001,Rash,NaT,2025-01-18,MODERATE,Not Related,Resolved,OK,OK,OK,False,False,True,False,False,False,1
2,AE-0003,SUB-004,Injection site reaction,NaT,2025-03-05,MODERATE,Related,Ongoing,OK,OK,OK,False,False,True,False,False,False,1
4,AE-0005,SUB-005,Diarrhea,NaT,2025-08-09,MODERATE,Not Related,Resolved,OK,OK,OK,False,False,True,False,False,False,1
6,AE-0007,SUB-007,Rash,2025-10-04,2025-04-29,MILD,Possibly Related,Ongoing,OK,OK,OK,False,False,False,False,False,True,1
7,AE-0008,SUB-011,Upper respiratory infection,NaT,2025-07-25,MODERATE,Possibly Related,Ongoing,OK,OK,OK,False,False,True,False,False,False,1
8,AE-0009,SUB-011,Back pain,2025-08-07,2025-07-16,MILD,Related,Resolved with sequelae,OK,OK,OK,False,False,False,False,False,True,1
9,AE-0010,SUB-012,Back pain,NaT,2025-08-10,SEVERE,Related,Resolving,OK,OK,OK,False,False,True,False,False,False,1
10,AE-0011,SUB-013,Back pain,NaT,2025-08-10,SEVERE,Related,Ongoing,OK,OK,OK,False,False,True,False,False,False,1
11,AE-0012,SUB-013,Dizziness,NaT,2025-07-11,SEVERE,Related,Resolving,OK,OK,OK,False,False,True,False,False,False,1
12,AE-0013,SUB-014,Insomnia,2025-02-09,2025-09-21,NaN,Possibly Related,Resolved,OK,QUERY,OK,False,False,False,True,False,False,1
15,AE-0016,SUB-018,Insomnia,NaT,2025-05-01,MILD,Not Related,Ongoing,OK,OK,OK,False,False,True,False,False,False,1
16,AE-0017,SUB-019,Fatigue,NaT,2025-09-03,MODERATE,Not Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False,1
17,AE-0018,SUB-020,Headache,NaT,2025-08-26,MILD,Possibly Related,Resolving,OK,OK,OK,False,False,True,False,False,False,1
18,AE-0019,SUB-021,Dizziness,NaT,2025-07-20,MODERATE,Possibly Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False,1
20,AE-0021,SUB-022,Upper respiratory infection,NaT,2025-10-07,SEVERE,Related,Resolved,QUERY,OK,OK,False,False,True,False,False,False,1
21,AE-0022,SUB-023,Headache,2025-11-04,2025-04-13,MILD,Not Related,Resolved,OK,OK,OK,False,False,False,False,False,True,1
23,AE-0024,SUB-026,Fatigue,NaT,2025-03-24,MILD,Not Related,Resolving,OK,OK,OK,False,False,True,False,False,False,1
25,AE-0026,SUB-026,Dizziness,NaT,2025-04-07,MODERATE,Not Related,Resolving,OK,OK,OK,False,False,True,False,False,False,1
26,AE-0027,SUB-027,Insomnia,NaT,2025-08-28,MODERATE,Possibly Related,Resolved,OK,OK,OK,False,False,True,False,False,False,1
27,AE-0028,SUB-029,Back pain,NaT,2025-03-11,MILD,Possibly Related,Ongoing,OK,OK,QUERY,False,False,True,False,False,False,1
28,AE-0029,SUB-031,Dizziness,NaT,2025-10-07,MILD,Not Related,Ongoing,OK,OK,OK,False,False,True,False,False,False,1
30,AE-0031,SUB-031,Upper respiratory infection,NaT,2025-08-03,SEVERE,Possibly Related,Resolved,OK,OK,OK,False,False,True,False,False,False,1
31,AE-0032,SUB-031,Diarrhea,NaT,2025-10-05,MODERATE,Possibly Related,Resolving,OK,OK,OK,False,False,True,False,False,False,1
32,AE-0033,SUB-032,Diarrhea,NaT,2025-06-02,MODERATE,Not Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False,1
33,AE-0034,SUB-033,Injection site reaction,NaT,2025-06-29,MODERATE,Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False,1
35,AE-0036,SUB-036,Rash,NaT,2025-07-18,SEVERE,Not Related,Ongoing,OK,OK,OK,False,False,True,False,False,False,1
37,AE-0038,SUB-043,Insomnia,NaT,2025-04-15,SEVERE,Related,Resolved,OK,OK,OK,False,False,True,False,False,False,1
38,AE-0039,SUB-044,Upper respiratory infection,NaT,2025-02-22,MILD,Related,Resolving,OK,OK,OK,False,False,True,False,False,False,1
39,AE-0040,SUB-045,Injection site reaction,2025-10-04,2025-04-26,NaN,Possibly Related,Resolved,OK,QUERY,OK,False,False,False,True,False,True,2
40,AE-0041,SUB-046,Dizziness,NaT,2025-06-01,MILD,Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False,1
41,AE-0042,SUB-047,Rash,NaT,2025-10-12,MODERATE,Not Related,Ongoing,OK,OK,OK,False,False,True,False,False,False,1
42,AE-0043,SUB-048,Headache,2025-10-07,2025-07-18,SEVERE,Not Related,Resolving,OK,OK,OK,False,False,False,False,False,True,1
43,AE-0044,SUB-050,Nausea,NaT,2025-06-30,MODERATE,Possibly Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False,1
44,AE-0045,SUB-051,Headache,2025-12-03,2025-03-26,SEVERE,Possibly Related,Ongoing,OK,OK,OK,False,False,False,False,False,True,1
45,AE-0046,SUB-052,Back pain,2025-04-04,2025-04-01,SEVERE,Not Related,Resolved with sequelae,OK,OK,QUERY,False,False,False,False,False,True,1
46,AE-0047,SUB-053,Insomnia,2025-07-04,2025-04-09,MILD,Related,Ongoing,OK,OK,OK,False,False,False,False,False,True,1
47,AE-0048,SUB-054,Diarrhea,2025-11-03,2025-03-21,MILD,Possibly Related,Resolving,OK,OK,OK,False,False,False,False,False,True,1
48,AE-0049,SUB-054,Dizziness,NaT,2025-04-25,SEVERE,Possibly Related,Resolved,OK,OK,OK,False,False,True,False,False,False,1
49,AE-0050,SUB-054,Rash,2025-11-03,2025-03-08,SEVERE,Not Related,Resolved with sequelae,OK,OK,QUERY,False,False,False,False,False,True,1
50,AE-0051,SUB-059,Upper respiratory infection,NaT,2025-03-04,SEVERE,Not Related,Resolved with sequelae,OK,OK,OK,False,False,True,False,False,False,1

In [53]:
# Count all laboratory data quality issues

lab_results["TOTAL_DQ_ISSUES"] = (
    lab_results["DUPLICATE_FLAG"].astype(int)
    +
    lab_results["DQ_RESULT_MISSING"].astype(int)
    +
    lab_results["DQ_RESULT_INVALID"].astype(int)
    +
    lab_results["DQ_UNIT_MISSING"].astype(int)
)

display(
    lab_results[
        lab_results["TOTAL_DQ_ISSUES"] > 0
    ]
)

,SUBJECT_ID,VISIT,VISIT_DATE,TEST_NAME,RESULT,UNIT,NORMAL_LOW,NORMAL_HIGH,RESULT_FLAG,DUPLICATE_FLAG,RESULT_NUMERIC,DQ_RESULT_MISSING,DQ_RESULT_INVALID,DQ_UNIT_MISSING,CLINICAL_FLAG,TOTAL_DQ_ISSUES
10,SUB-001,Week 8,2025-06-04,ALT,NaN,U/L,7.0,56.0,MISSING,False,NaN,True,False,False,NORMAL,1
21,SUB-002,Baseline,2025-10-03,AST,NaN,U/L,8.0,48.0,MISSING,False,NaN,True,False,False,NORMAL,1
148,SUB-008,Week 8,NaT,WBC,NaN,10^9/L,4.0,11.0,MISSING,False,NaN,True,False,False,NORMAL,1
187,SUB-010,Week 12,2025-03-08,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL,1
222,SUB-012,Week 12,2025-12-09,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL,1
223,SUB-012,Week 12,2025-12-09,WBC,NaN,10^9/L,4.0,11.0,MISSING,False,NaN,True,False,False,NORMAL,1
348,SUB-019,Week 12,NaT,WBC,NaN,10^9/L,4.0,11.0,MISSING,False,NaN,True,False,False,NORMAL,1
358,SUB-020,Week 4,NaT,WBC,NaN,10^9/L,4.0,11.0,MISSING,False,NaN,True,False,False,NORMAL,1
372,SUB-021,Baseline,2025-11-05,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL,1
468,SUB-026,Week 4,2025-08-04,WBC,NaN,10^9/L,4.0,11.0,MISSING,False,NaN,True,False,False,NORMAL,1
505,SUB-028,Week 8,NaT,ALT,NaN,U/L,7.0,56.0,MISSING,False,NaN,True,False,False,NORMAL,1
515,SUB-029,Week 4,2025-07-04,ALT,NaN,U/L,7.0,56.0,MISSING,False,NaN,True,False,False,NORMAL,1
517,SUB-029,Week 4,2025-07-04,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL,1
538,SUB-030,Week 4,NaT,WBC,NaN,10^9/L,4.0,11.0,MISSING,False,NaN,True,False,False,NORMAL,1
567,SUB-032,Baseline,2025-12-05,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL,1
576,SUB-032,Week 8,2025-07-07,AST,NaN,U/L,8.0,48.0,MISSING,False,NaN,True,False,False,NORMAL,1
586,SUB-033,Baseline,NaT,AST,NaN,U/L,8.0,48.0,MISSING,False,NaN,True,False,False,NORMAL,1
597,SUB-033,Week 8,NaT,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL,1
662,SUB-036,Week 12,NaT,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL,1
682,SUB-038,Baseline,2025-12-06,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL,1
776,SUB-043,Week 4,NaT,AST,NaN,U/L,8.0,48.0,MISSING,False,NaN,True,False,False,NORMAL,1
800,SUB-044,Week 12,NaT,ALT,NaN,U/L,7.0,56.0,MISSING,False,NaN,True,False,False,NORMAL,1
845,SUB-047,Week 8,NaT,ALT,NaN,U/L,7.0,56.0,MISSING,False,NaN,True,False,False,NORMAL,1
854,SUB-047,Week 12,NaT,Creatinine,NaN,mg/dL,0.6,1.3,MISSING,False,NaN,True,False,False,NORMAL,1
899,SUB-050,Baseline,2025-03-07,Creatinine,NaN,mg/dL,0.6,1.3,MISSING,False,NaN,True,False,False,NORMAL,1
1045,SUB-058,Week 4,2025-05-09,ALT,NaN,U/L,7.0,56.0,MISSING,False,NaN,True,False,False,NORMAL,1
1072,SUB-059,Week 8,NaT,Hemoglobin,NaN,g/dL,12.0,17.5,MISSING,False,NaN,True,False,False,NORMAL,1

In [54]:
# Create an empty list to store all data queries

queries = []

In [55]:
def add_query(subject_id, dataset, field, issue):

    queries.append({
        "SUBJECT_ID": subject_id,
        "DATASET": dataset,
        "FIELD": field,
        "ISSUE": issue,
        "STATUS": "Open"
    })

In [56]:
for _, row in demographics.iterrows():

    if row["DUPLICATE_FLAG"]:
        add_query(
            row["SUBJECT_ID"],
            "Demographics",
            "SUBJECT_ID",
            "Duplicate subject record"
        )

    if row["DQ_AGE_MISSING"]:
        add_query(
            row["SUBJECT_ID"],
            "Demographics",
            "AGE",
            "Age is missing"
        )

    if row["DQ_AGE_RANGE"]:
        add_query(
            row["SUBJECT_ID"],
            "Demographics",
            "AGE",
            "Age is outside the expected range"
        )

In [57]:
for _, row in vitals.iterrows():

    if row["DUPLICATE_FLAG"]:
        add_query(
            row["SUBJECT_ID"],
            "Vitals",
            "Record",
            "Duplicate vital sign record"
        )

    if row["DQ_SYSTOLIC_MISSING"]:
        add_query(
            row["SUBJECT_ID"],
            "Vitals",
            "SYSTOLIC_BP",
            "Systolic BP is missing or invalid"
        )

    if row["DQ_PULSE_RANGE"]:
        add_query(
            row["SUBJECT_ID"],
            "Vitals",
            "PULSE",
            "Pulse is outside the expected range"
        )

    if row["DQ_BP_LOGIC"]:
        add_query(
            row["SUBJECT_ID"],
            "Vitals",
            "BLOOD_PRESSURE",
            "Diastolic BP is greater than or equal to systolic BP"
        )

    if row["DQ_VISIT_BEFORE_ENROLL"]:
        add_query(
            row["SUBJECT_ID"],
            "Vitals",
            "VISIT_DATE",
            "Visit date occurs before enrollment date"
        )

In [58]:
for _, row in adverse_events.iterrows():

    if row["DQ_AE_TERM_MISSING"]:
        add_query(
            row["SUBJECT_ID"],
            "Adverse Events",
            "AE_TERM",
            "Adverse event term is missing"
        )

    if row["DQ_SEVERITY_INVALID"]:
        add_query(
            row["SUBJECT_ID"],
            "Adverse Events",
            "SEVERITY",
            "Invalid severity value"
        )

    if row["DQ_DATE_LOGIC"]:
        add_query(
            row["SUBJECT_ID"],
            "Adverse Events",
            "END_DATE",
            "End date occurs before start date"
        )

In [59]:
for _, row in lab_results.iterrows():

    if row["DQ_RESULT_MISSING"]:
        add_query(
            row["SUBJECT_ID"],
            "Lab Results",
            "RESULT",
            "Laboratory result is missing"
        )

    if row["DQ_RESULT_INVALID"]:
        add_query(
            row["SUBJECT_ID"],
            "Lab Results",
            "RESULT",
            "Laboratory result is invalid"
        )

    if row["DQ_UNIT_MISSING"]:
        add_query(
            row["SUBJECT_ID"],
            "Lab Results",
            "UNIT",
            "Laboratory unit is missing"
        )

In [60]:
query_listing = pd.DataFrame(queries)

# Create query IDs
query_listing.insert(
    0,
    "QUERY_ID",
    [f"Q{i:03d}" for i in range(1, len(query_listing) + 1)]
)

# Display final query listing
query_listing

,QUERY_ID,SUBJECT_ID,DATASET,FIELD,ISSUE,STATUS
0,Q001,SUB-001,Demographics,AGE,Age is outside the expected range,Open
1,Q002,SUB-018,Demographics,AGE,Age is missing,Open
2,Q003,SUB-024,Demographics,AGE,Age is outside the expected range,Open
3,Q004,SUB-035,Demographics,AGE,Age is missing,Open
4,Q005,SUB-047,Demographics,AGE,Age is outside the expected range,Open
...,...,...,...,...,...,...
109,Q110,SUB-047,Lab Results,RESULT,Laboratory result is missing,Open
110,Q111,SUB-047,Lab Results,RESULT,Laboratory result is missing,Open
111,Q112,SUB-050,Lab Results,RESULT,Laboratory result is missing,Open
112,Q113,SUB-058,Lab Results,RESULT,Laboratory result is missing,Open
113,Q114,SUB-059,Lab Results,RESULT,Laboratory result is missing,Open